# Azure DevOps Build Pipeline for test-CI container
# Trying to prevent all the docker labels ADO likes to inject into the images
# DEBUG: Not sure wth its doing with vars atm....

name: $(BuildDefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

variables:
  system.debug: false
  CI_PLATFORM: azure-pipelines
  IMAGE_NAME: jsloan117/test-ci
  ADO_BRANCH: $(Build.SourceBranchName)

schedules:
  - cron: '0 0 * * 6'
    displayName: 'Weekly build at midnight'
    branches:
      include:
        - '*'
    always: true

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Docker login
    inputs:
      containerRegistry: 'Docker Hub'
      command: login
    enabled: false

  - task: Bash@3
    displayName: Install latest version of docker
    condition: succeeded()
    inputs:
      targetType: inline
      script: |
        sudo apt-get update
        sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update && sudo apt-get -y install docker-ce docker-ce-cli containerd.io
        sudo systemctl enable --now docker.service
    enabled: true

  - task: Bash@3
    displayName: Get environment info
    condition: succeeded()
    inputs:
      targetType: inline
      script: |
        env
        docker --version
        printf "\n\n\n"
        docker info
    enabled: false

  - task: Bash@3
    displayName: Set image tag
    condition: succeeded()
    inputs:
      targetType: inline
      script: |
        printf '\n<<< Setting image tag >>>\n\n'
        if [ "$ADO_BRANCH" == "master" ]; then IMAGE_TAG=latest; else IMAGE_TAG=$ADO_BRANCH; fi
        printf "\nImage tag is $IMAGE_TAG\n"
        echo "##vso[task.setvariable variable=IMAGE_TAG]$IMAGE_TAG"
    enabled: true

  - task: Bash@3
    displayName: Build docker images
    condition: succeeded()
    inputs:
      targetType: inline
      script: |
        printf '\n<<< Building image >>>\n\n'
        sudo docker build -f Dockerfile -t "$IMAGE_NAME:$CI_PLATFORM-$IMAGE_TAG" .
    enabled: true

  - task: Bash@3
    displayName: Build ubuntu docker images
    condition: succeeded()
    inputs:
      targetType: inline
      script: |
        printf '\n<<< Building ubuntu image >>>\n\n'
        sudo docker build -f Dockerfile.ubuntu -t "$IMAGE_NAME:ubuntu-$CI_PLATFORM-$IMAGE_TAG" .
    enabled: true

  - task: Bash@3
    displayName: Inspect image labels
    condition: succeeded()
    inputs:
      targetType: inline
      script: |
        printf '\n<<< Inspecting images >>>\n\n'
        for img in $(sudo docker images | awk '{OFS = ":";} {print $1,$2}' | tail -n+2 | head -n2); do 
          sudo docker image inspect -f '{{json .Config.Labels}}' "${img}"; printf '\n'; 
        done
    enabled: true

  - task: Bash@3
    displayName: Build documentation
    condition: succeeded()
    inputs:
      targetType: inline
      script: |
        printf '\n<<< Building documentation >>>\n\n'
        sudo docker run --rm -v $(pwd):/docs jsloan117/docker-mkdocs mkdocs build
    enabled: true

  - task: Bash@3
    displayName: Pull request review
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      targetType: inline
      script: |
        printf '\n<<< Do stuff because of a PR >>>\n\n'
    enabled: true

  - task: Docker@2
    displayName: Docker logout
    inputs:
      containerRegistry: 'Docker Hub'
      command: logout
    enabled: false
