---
kind: pipeline
type: docker
name: Build Docker Images

steps:
- name: build docker images
  image: plugins/docker
  environment:
    DOCKER_USER: jsloan117
    DOCKER_REPO:
      from_secret: docker_repo
    DOCKERFILE: Dockerfile
  commands:
    - echo '<<< Building docker images >>>'
    - if [ "$DRONE_BRANCH" == "master" ]; then docker build -f $DOCKERFILE -t $DOCKER_USER/$DOCKER_REPO:ubuntu-latest .; fi
    - if [ "$DRONE_BRANCH" != "master" ]; then docker build -f $DOCKERFILE -t $DOCKER_USER/$DOCKER_REPO:ubuntu-$DRONE_BRANCH .; fi

- name: build alternative docker images
  image: plugins/docker
  environment:
    DOCKER_USER: jsloan117
    DOCKER_REPO:
      from_secret: docker_repo
    DOCKERFILE: Dockerfile.ubuntu
  commands:
    - echo '<<< Building alternative docker images >>>'
    - if [ "$DRONE_BRANCH" == "master" ]; then docker build -f $DOCKERFILE -t $DOCKER_USER/$DOCKER_REPO:ubuntu-latest .; fi
    - if [ "$DRONE_BRANCH" != "master" ]; then docker build -f $DOCKERFILE -t $DOCKER_USER/$DOCKER_REPO:ubuntu-$DRONE_BRANCH .; fi
