pipeline:
  set-image-tag:
    image:  plugins/docker
    commands:
      - |
        echo 'CI_PLATFORM=droneio' > import.vars
        echo 'IMAGE_NAME=jsloan117/test-ci' >> import.vars
        if [ $DRONE_BRANCH = master ]; then IMAGE_TAG=latest; else IMAGE_TAG=$DRONE_BRANCH; fi
        echo "IMAGE_TAG=$IMAGE_TAG" >> import.vars

  build-image:
    image:  plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - |
        source import.vars
        docker build -f Dockerfile -t $IMAGE_NAME:$CI_PLATFORM-$IMAGE_TAG .

  build-ubuntu-image:
    image:  plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - |
        source import.vars
        docker build -f Dockerfile.ubuntu -t $IMAGE_NAME:ubuntu-$CI_PLATFORM-$IMAGE_TAG .
