---
kind: pipeline
type: docker
name: Build Docker Images

steps:
- name: build docker images
  image: plugins/docker
  environment:
    DOCKER_USER: jsloan117
    DOCKER_REPO:
      from_secret: docker_repo
    DOCKERFILE: Dockerfile
    IMAGE_NAME: jsloan117/test-ci
  commands:
    - echo "<<< Building docker images >>>"
    - if [ "$DRONE_BRANCH" == "master" ]; then docker build -f $DOCKERFILE -t $IMAGE_NAME:latest .; fi
    - if [ "$DRONE_BRANCH" != "master" ]; then docker build -f $DOCKERFILE -t $IMAGE_NAME:$DRONE_BRANCH .; fi

- name: build alternative docker images
  image: plugins/docker
  environment:
    DOCKER_USER: jsloan117
    DOCKER_REPO:
      from_secret: docker_repo
    DOCKERFILE: Dockerfile.ubuntu
    IMAGE_NAME: jsloan117/test-ci
  commands:
    - echo "<<< Building alternative docker images >>>"
    - if [ "$DRONE_BRANCH" == "master" ]; then docker build -f $DOCKERFILE -t $IMAGE_NAME:ubuntu-latest .; fi
    - if [ "$DRONE_BRANCH" != "master" ]; then docker build -f $DOCKERFILE -t $IMAGE_NAME:ubuntu-$DRONE_BRANCH .; fi

- name: publish documentation
  image: plugins/gh-release
  settings:
    pages_directory: site/
  when:
    branch:
    - master
