language: python
python: 3.7
services: docker
dist: bionic
#addons:
#  apt:
#    packages:
#      - python3-pip

env:
  global:
    - DOCKER_USER=jsloan117
    - DOCKER_PASS=
    - DOCKER_REPO=test-ci
    - IMAGE_NAME=jsloan117/test-ci
    - CI_PLATFORM=travisci

jobs:
  include:
    - stage: build docker images
      script: |
        printf '\n<<< building image >>>\n\n'
        if [ "$TRAVIS_BRANCH" == "master" ]; then IMAGE_TAG=latest; else IMAGE_TAG=$TRAVIS_BRANCH; export IMAGE_TAG; fi
        docker build -f Dockerfile -t $IMAGE_NAME:$CI_PLATFORM-$IMAGE_TAG .
        if [ "${TRAVIS_PULL_REQUEST}" != "true" ]; then
          echo "I would be logging in and pushing stuff................"
        else
          echo "Not pushing PR's"
          exit 0
        fi

    - stage: build ubuntu docker images
      script: |
        printf '\n<<< building ubuntu image >>>\n\n'
        if [ "$TRAVIS_BRANCH" == "master" ]; then IMAGE_TAG=latest; else IMAGE_TAG=$TRAVIS_BRANCH; export IMAGE_TAG; fi
        docker build -f Dockerfile.ubuntu -t $IMAGE_NAME:ubuntu-$CI_PLATFORM-$IMAGE_TAG .
        if [ "${TRAVIS_PULL_REQUEST}" != "true" ]; then
          echo "I would be logging in and pushing stuff................"
        else
          echo "Not pushing PR's"
          exit 0
        fi

    - stage: push images
      script: |
        docker images

#    - stage: build documentation
#      if: branch = dev
#      script: |
#        pip install mkdocs mkdocs-material
#        mkdocs build --verbose --clean --strict

before_deploy:
#  - pyenv global 3.7.5
  - python --version
  - pip3 install mkdocs mkdocs-material
  - mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  cleanup: false
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  local_dir: site
  committer_from_gh: true
  on:
    branch: dev
