sudo: required

dist: xenial

services:
  - docker

env:
  global:
    - DOCKER_USER=jsloan117
    - DOCKER_PASS=
    - DOCKER_REPO=test-ci
    - IMAGE_NAME=$DOCKER_USER/$DOCKER_REPO
#    - DOCKERFILE=Dockerfile

#install: skip

jobs:
  include:
 #   - stage: Set image tag
 #     script: |
 #       echo -e '\n<<< Setting docker image tag format >>>\n'
 #       if [ "$TRAVIS_BRANCH" == "master" ]; then IMAGE_TAG=lastest; else IMAGE_TAG=$TRAVIS_BRANCH; fi
 #       echo $IMAGE_TAG; export IMAGE_TAG

    - stage: build docker image
      script: |
        if [ "$TRAVIS_BRANCH" == "master" ]; then IMAGE_TAG=lastest; else IMAGE_TAG=$TRAVIS_BRANCH; fi
        export IMAGE_TAG
        echo -e '\n<<< Building default docker images >>>\n'
        docker build -f Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .

    - stage: build alt docker image
      env:
        - DOCKERFILE=Dockerfile.ubuntu
        - DIST=ubuntu
      script: |
        if [ "$TRAVIS_BRANCH" == "master" ]; then IMAGE_TAG=lastest; else IMAGE_TAG=$TRAVIS_BRANCH; fi
        export IMAGE_TAG
        echo -e '\n<<< Building alternative docker images >>>\n'
        docker build -f Dockerfile.ubuntu -t $IMAGE_NAME:$DIST-$IMAGE_TAG

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN
  keep_history: true
  #local_dir: site
  committer_from_gh: true
  on:
    branch: master
