language: shell
os: linux
dist: bionic

env:
  global:
    - IMAGE_NAME=jsloan117/test-ci
    - CI_PLATFORM=travisci

jobs:
  include:
    - stage: build docker images
      services: docker
      script: ./scripts/build-and-push.sh

    - stage: build documentation
      if: branch = master
      language: python
      python: 3.7.5
      cache: pip
      #script: ./scripts/doc-build-and-deploy.sh
      install: pip3 install mkdocs mkdocs-material pymdown-extensions pygments
      before_deploy: mkdocs build -vc
      deploy:
        provider: pages
        cleanup: false
        token: $GIT_TOKEN
        keep_history: false
        local_dir: site
        name: "Travis CI"
        on:
          branch: master
