language: minimal
services: docker
dist: bionic
sudo: required

env:
  global:
    - DOCKER_USER=jsloan117
    - DOCKER_PASS=
    - DOCKER_REPO=test-ci
    - IMAGE_NAME=$DOCKER_USER/$DOCKER_REPO

jobs:
  include:
    - stage: build docker images
      env:
        - CI_PLATFORM=travisci
      script: |
        if [ "$TRAVIS_BRANCH" == "master" ]; then IMAGE_TAG=latest; else IMAGE_TAG=$TRAVIS_BRANCH; export IMAGE_TAG; fi
        docker build -f Dockerfile -t $IMAGE_NAME:$CI_PLATFORM-$IMAGE_TAG .

    - stage: build ubuntu docker images
      env:
        - DOCKERFILE=Dockerfile.ubuntu
        - CI_PLATFORM=travisci
      script: |
        if [ "$TRAVIS_BRANCH" == "master" ]; then IMAGE_TAG=latest; else IMAGE_TAG=$TRAVIS_BRANCH; export IMAGE_TAG; fi
        docker build -f Dockerfile.ubuntu -t $IMAGE_NAME:ubuntu-$CI_PLATFORM-$IMAGE_TAG .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN
  keep_history: true
  #local_dir: site
  committer_from_gh: true
  on:
    branch: master
