---
platform: linux

resouces:
- name: test-ci
  type: git
  source:
    uri: https://github.com/jsloan117/test-CI.git
    branch: dev

#image_resouce:
#  type: docker-image
#  source:
#    repository: docker
#    tag: stable-dind

- name: test-ci-image
  type: docker-image
  source:
    repository: jsloan117/test-ci

jobs:
- name: build docker images
  build_log_retention:
    days: 60
    builds: 1000
  max_in_flight:  2
  public: true
  plan:
  - get:  test-ci
    trigger:  true

#  - put: test-ci-image
#    params:
#      build: test-ci
