---
name: Build Docker Images

on:
  push:
    branches:
      - dev
      - master
    paths-ignore:
    - 'docs/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: jsloan117/test-ci

jobs:
  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.IMAGE_NAME }}
          tag-sha: false
          tag-semver: |
            {{version}}

      - name: Set latest image tag
        if: github.ref == 'refs/heads/master'
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      - name: Set non-latest image tag
        if: github.ref != 'refs/heads/master'
        run: IMAGE_TAG=$(echo $GITHUB_REF | cut -d'/' -f3) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: jsloan117
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Alpine
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Build and push Ubuntu
        id: docker_build_ubuntu
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.ubuntu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-ubuntu
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          echo ${{ steps.docker_build_ubuntu.outputs.digest }}
