---
name: Build Docker Images

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: jsloan117/test-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
        fetch-depth: 0

      - name: Set latest image tag
        if: github.ref == 'refs/heads/master'
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      - name: Set other image tag
        if: github.ref != 'refs/heads/master'
        run: IMAGE_TAG=$(echo $GITHUB_REF | cut -d'/' -f3) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: jsloan117
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${IMAGE_NAME}:gh-${IMAGE_TAG}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
