name: prlabeler

on:
  - pull_request_target

jobs:
  prlabeler:
    name: pull request labeler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GH_PAT }}"
