---
name: Tag & Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - mkdocs.yml
      - README.md

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2.4.0

      # https://github.com/marketplace/actions/github-tag
      # https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          default_bump: patch
          github_token: ${{ secrets.GH_PAT }}
          tag_prefix: v

      # https://github.com/marketplace/actions/create-release
      # https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
      - name: Create release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          # body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
