---
name: devimages

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - 'mkdocs.yml'

jobs:
  build:
    name: dev build & push
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: '0'

      - name: docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.3.0
        with:
          images: jsloan117/test-ci
          tag-sha: false
          tag-semver: |
            {{version}}

      - name: set up qemu
        uses: docker/setup-qemu-action@v1.2.0

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1.4.1

      - name: login to dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0 
        with:
          username: jsloan117
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: alpine
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: ubuntu
        id: docker_build_ubuntu
        uses: docker/build-push-action@v2.5.0
        with:
          file: ./Dockerfile.ubuntu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}-ubuntu
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          echo ${{ steps.docker_build_ubuntu.outputs.digest }}
